auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    s3:
      endpoint: http://localstack:4566
      bucketnames: loki-chunks
      region: us-east-1
      access_key_id: test
      secret_access_key: test
      s3forcepathstyle: true
      insecure: true
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
