FROM golang:1.23-alpine AS builder

WORKDIR /build


COPY go.mod go.sum* ./
RUN go mod download

COPY . .


RUN CGO_ENABLED=0 GOOS=linux go build -o stresser .


FROM alpine:3.19

WORKDIR /app

COPY --from=builder /build/stresser .

COPY --from=builder /build/static ./static

EXPOSE 8080

CMD ["./stresser"]