{
 "title": "Golden Singnals",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Metrics",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stress Level",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stress_level", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Workers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stress_cpu_workers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Failed Traces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ resource.service.name = \"stresser-app\" && (status = error || span.http.status_code >= 500) }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Slowest Request Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "filters": [
      { "id": "282abdf5", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "stresser-app" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "stresser-app" ],
       "valueType": "string"
      },
      {
       "id": "status",
       "isCustomValue": false,
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "value": "unset",
       "valueType": "keyword"
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "100ms",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ resource.service.name = \"stresser-app\" && duration > 200ms }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Logs Timelines",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=~\".+\"}"
    }
   ]
  }
 ]
}